# Default GGUF Models Sync Configuration
# This is the main configuration file for the GGUF models synchronization system

# Environment and basic settings
environment: production
log_level: INFO
debug_mode: false
dry_run: false

# API and external service settings
api_base_url: "https://huggingface.co"
user_agent: "GGUF-Models-Sync/1.0"

# Workflow and deployment settings
workflow_timeout_hours: 6
enable_github_actions_integration: true
enable_pages_deployment: true

# Rate limiting configuration - Fail fast for debugging
rate_limiting:
  requests_per_second: 2.0  # Increased from 1.2
  requests_per_hour: 5000
  max_concurrent_requests: 25  # Reduced to avoid overwhelming API
  backoff_base: 1.5  # Reduced from 2.0
  backoff_jitter: true
  max_retries: 1  # No retries - fail fast
  timeout_seconds: 20  # Reduced from 30

# Sync behavior configuration - Optimized for speed
sync_behavior:
  mode: full  # auto, incremental, full
  incremental_window_hours: 48
  full_sync_threshold_hours: 168  # Weekly full sync
  significant_change_threshold: 0.1  # 10% change triggers full sync
  force_full_sync: true
  enable_multi_strategy_discovery: false  # DISABLED for speed - use only primary GGUF filter
  enable_deduplication: true

# Data validation configuration
validation:
  enable_schema_validation: true
  enable_file_verification: true
  enable_completeness_checking: true
  min_completeness_score: 0.95
  enable_quality_scoring: true
  enable_automatic_fixes: true
  validation_timeout_seconds: 300

# Error handling configuration - Fail fast for debugging
error_handling:
  enable_error_recovery: false  # Disabled for debugging
  enable_exponential_backoff: false  # Disabled for debugging
  enable_categorized_errors: true
  enable_notifications: true
  max_recovery_attempts: 1  # No retries
  recovery_delay_seconds: 0  # No delays
  preserve_data_on_failure: true

# Monitoring and alerting configuration
monitoring:
  enable_detailed_logging: true
  enable_progress_tracking: true
  progress_report_interval_seconds: 900  # 15 minutes
  enable_performance_metrics: true
  enable_alerts: true
  alert_channels:
    - log
    - github
  enable_dashboard: false

# Performance optimization configuration - Optimized for speed
performance:
  enable_streaming_processing: true
  enable_data_compression: false  # Disabled to reduce processing time
  enable_caching: true
  cache_ttl_hours: 24
  memory_limit_mb: 2048
  enable_parallel_processing: true
  chunk_size: 200  # Increased from 100 for better batching
  enable_adaptive_parameters: false  # Disabled to reduce overhead

# Storage configuration
storage:
  data_directory: "data"
  backup_directory: "data/backups"
  reports_directory: "reports"
  logs_directory: "logs"
  enable_backups: true
  backup_retention_days: 30
  enable_compression: true

# Notification configuration
notifications:
  enable_success_notifications: false
  enable_failure_notifications: true
  enable_warning_notifications: true
  enable_critical_notifications: true
  notification_channels:
    - log
  webhook_urls: []
  email_recipients: []

# Security configuration
security:
  enable_token_validation: true
  enable_rate_limit_protection: true
  enable_request_signing: false
  enable_audit_logging: true
  mask_sensitive_data: true
  allowed_domains:
    - "huggingface.co"

# Dynamic retention configuration
dynamic_retention:
  retention_days: 30
  top_models_count: 20
  update_schedule_cron: "0 2 * * *"  # Daily at 2 AM
  enable_cleanup: true
  cleanup_batch_size: 100
  preserve_download_threshold: 1000
  enable_ranking_history: true
  ranking_history_days: 90
  enable_retention_mode: false  # Disabled by default
  recent_models_priority: true
  top_models_storage_path: "data/top_models.json"
  retention_metadata_path: "data/retention_metadata.json"

# Custom settings for extensibility
custom_settings: {}